name: Matrix Configuration

on:
   #push:
   workflow_dispatch:

jobs:
    deploy:
        strategy:
            matrix:
# this is not a tag but whatever you want to use, docker comes preinstalled on all virtual machines
                os: [ubuntu-latest, ubunut-20.04, windows-latest] 
                images: [hello-world, alpine] 
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo Docker Details
          run: docker info
          
        - name: Run Images
          run: docker run ${{ matrix.iamges }}
# the above will create 5 different jobs because there are 3 OS X 2 images = 6 images running in parallel
